# Reusable Action
name: Build Docker Image
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      context_path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context_path }}
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ inputs.image_name }}:latest
            ghcr.io/${{ github.repository }}/${{ inputs.image_name }}:${{ github.sha }}
          cache-from: type=gha,scope=${{ inputs.image_name }}
          cache-to: type=gha,mode=max,scope=${{ inputs.image_name }}