name: Build Classifier Images
on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths:
      - 'models/classification/**'

jobs:
  build-classifier-image:
    uses: ./.github/workflows/build-docker-image.yaml
    with:
      image_name: "classifier"
      dockerfile_path: "./models/classification/Dockerfile"
      context_path: "./models/classification"
      image_tag_suffix: "classifier"
      